
#FPS Monitor - Settings File
[display]
	#Display Pos - Horizontal [0 = LEFT]
	display_pos_x = 2
	#Display Pos - Vertical [0 = TOP]
	display_pos_y = 2
	#Text Transparency [0 = INVISIBLE | 255 = SOLID]
	#Range: 0 ~ 255
	text_transparency = 215
	#Text Shadow [Applies Drop-Shadow to Font]
	has_text_shadow = true
	#Displays Information on the Game-Window Bar
	game_window_info = true

[components]

	[components.fps]
		#Toggles FPS HUD
		toggle_fps = true
		#Selects FPS Font Color
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, CYAN, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
		color = "CYAN"

	[components.ping]
		#Toggles Ping HUD
		toggle_ping = false
		#Selects Ping Font Color
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, CYAN, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
		color = "LIGHT_PURPLE"

	[components.memory]
		#Toggles Memory HUD
		toggle_memory = false
		#Selects Memory Font Color
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, CYAN, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
		color = "GOLD"

