name: Package Modpack

on:
  push:
    branches:
      - 1.19.4-OptiFabric-Dev
  workflow_dispatch:

jobs:
  Build-Modpack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
          
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
        if: ${{ github.repository_owner != 'github-actions' }}

      - run: git config user.name "${{ github.actor }}"
        if: ${{ github.repository_owner != 'github-actions' }}   
        
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Append short SHA to file content
        run: |
          sed -i "s/\(buildtype\)/${{ env.SHORT_SHA }}/g" modrinth.index.json
          sed -i "s/\(buildtype\)/${{ env.SHORT_SHA }}/g" ./overrides/config/modpack-update-checker/config.json
      
      - name: Package Modpack
        run: |
          rm -rf .github
          rm -rf .git
          rm README.md
          rm English.md
          rm meta.json
          cd overrides
          cd config
          mv emi.byd emi.css 
          cd slightguimodifications
          mv cts.byd cts.groovy
          cd ..
          cd ..
          cd ..
          zip -r "./MineOptimiz.zip" ./*
          mv *.zip "MineOptimiz OptiFabric v1.19.4-Dev-${{ env.SHORT_SHA }}.mrpack"
      
      - uses: actions/upload-artifact@v2
        with:
          name: MineOptimiz OptiFabric v1.19.4-Dev-${{ env.SHORT_SHA }}.zip
          path: "./MineOptimiz OptiFabric v1.19.4-Dev-${{ env.SHORT_SHA }}.mrpack"
     