name: Package Modpack

on:
  push:
    branches:
      - 1.20.1-Dev
  workflow_dispatch:

jobs:
  Package-Modpack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
          
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
        if: ${{ github.repository_owner != 'github-actions' }}

      - run: git config user.name "${{ github.actor }}"
        if: ${{ github.repository_owner != 'github-actions' }}   
        
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Append short SHA to file content
        run: |
          sed -i "s/\(buildtype\)/${{ env.SHORT_SHA }}/g" modrinth.index.json
          sed -i "s/\(buildtype\)/${{ env.SHORT_SHA }}/g" ./overrides/config/modpack-update-checker/config.json
      
      - name: Package Modpack
        run: |
          rm -rf .github
          rm -rf .git
          rm README.md
          cd overrides
          mv h.txt options.txt
          cd config
          cd slight*
          mv *.byd cts.groovy
          cd ..
          cd ..
          cd ..
          zip -r "./MineOptimiz.zip" ./*
          mv MineOptimiz.zip "MineOptimiz Fabric 1.20.1-Dev-${{ env.SHORT_SHA }}.mrpack"
      
      - uses: actions/upload-artifact@v2
        with:
          name: MineOptimiz Fabric 1.20.1-Dev-${{ env.SHORT_SHA }}.zip
          path: "./MineOptimiz Fabric 1.20.1-Dev-${{ env.SHORT_SHA }}.mrpack"
     
